### ISSUE TITLE
Fix resource leak in DPL_APPEND_STR macro

### ISSUE THREAD

**Issue by Joacchim** [scality/Droplet#198]
The commit 8b2288c314bdd2b9debe38b2b0b7c5d57e58c872 attempted to address the leak, but failed to properly fix the thing.

It actually fixed the leak by calling a function instead of a macro that returned an error in case of failure, and checking the return value of this macro in part of the places. The issue was that this macro was used in a number of places,  using length types ranging from int, unsigned int, size_t and so on.

This led to another potential error in some non-fixed places in the droplet library: the implicit erroneous cast to size_t* from int* or unsigned int* meant that a memory overrun could easily occur on 64bits systems (which is the main target of this library)

The patch was a good idea, but incomplete, and must be reworked and improved.

**Comment by QuentinPerez** [comment]
Hi @Joacchim,

Normally, I fixed it in my second PR ?

**Comment by Joacchim** [comment]
I think the second PR was rejected (AFAIR), so It was not part of my considerations for the revert. For the revert my consideration, more than the leak was to avoid any risk of silent failure, which is not completely/properly addressed by the reverted patch, and neither it is by the patch you mention.

ie, looking at the patch you point to quickly, I still see an issue: The DPL_APPEND_STR macro's returned value is not checked in those two files, creating a silent error.

What we want to make sure for this patch is:
 * Create a consistent use of the type of "length" variables throughout the codebase, in order for the DPL_APPEND_STR macro to become a function instead of a macro (we could as well remove the macro altogether for clarity).
 * Avoid any silent error: Check properly the returned status of the dpl_append_str function, in order to manage properly any failure that could arise (hence the leak fix)

**Comment by QuentinPerez** [comment]
Nice, No problem I understand :)
And my bad for the white spaces, it was my editor that removes it when I save a file.
